server:
  port: 8080
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/student?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    thymeleaf:
      prefix: classpath:/templates/
      suffix: .html
mybatis:
  type-aliases-package: com.example.springbootajax.pojo
  mapper-locations: classpath:/mybatis/*.xml
